import { ProductSpecFormValues } from '@/utils/schema/productSpec.form.schema';

export function productSpecdefaultValues(
  initialProductSpecData: ProductSpecFormValues
) {
  return {
    /* specification section */
    construction: initialProductSpecData?.construction ?? '',
    dimension: initialProductSpecData?.dimension ?? '',
    base: initialProductSpecData?.base ?? '',
    position: initialProductSpecData?.position ?? '',
    bodyFrame: initialProductSpecData?.bodyFrame ?? '',
    itemFunctions: initialProductSpecData?.itemFunctions ?? '',
    item_type: initialProductSpecData?.item_type ?? '',
    item_model: initialProductSpecData?.item_model ?? '',
    mattress: initialProductSpecData?.mattress ?? '',
    mattressSize: initialProductSpecData?.mattressSize ?? '',
    mattressThickness: initialProductSpecData?.mattressThickness ?? '',
    finishing: initialProductSpecData?.finishing ?? '',
    powerSupply: initialProductSpecData?.powerSupply ?? '',
    loadCapacity: initialProductSpecData?.loadCapacity ?? '',
    systemFilter: initialProductSpecData?.systemFilter ?? '',
    accessories: initialProductSpecData?.accessories ?? '',
    sideRail: initialProductSpecData?.sideRail ?? '',
    ivStand: initialProductSpecData?.ivStand ?? '',
    wheels: initialProductSpecData?.wheels ?? '',
    maxLoad: initialProductSpecData?.maxLoad ?? '',
    size: initialProductSpecData?.size ?? '',
    weight: initialProductSpecData?.weight ?? '',
    standSize: initialProductSpecData?.standSize ?? '',
    basePlate: initialProductSpecData?.basePlate ?? '',
    cover: initialProductSpecData?.cover ?? '',
    material: initialProductSpecData?.material ?? '',
    coverMaterial: initialProductSpecData?.coverMaterial ?? '',
    typeScreen: initialProductSpecData?.typeScreen ?? '',
    powerConsumption: initialProductSpecData?.powerConsumption ?? '',
    lamp: initialProductSpecData?.lamp ?? '',
    movers: initialProductSpecData?.movers ?? '',
    rim: initialProductSpecData?.rim ?? '',
    custodyFeet: initialProductSpecData?.custodyFeet ?? '',
    foot: initialProductSpecData?.foot ?? '',
    footWear: initialProductSpecData?.footWear ?? '',
    pole: initialProductSpecData?.pole ?? '',
    inputVoltage: initialProductSpecData?.inputVoltage ?? '',
    outputVoltage: initialProductSpecData?.outputVoltage ?? '',
    sideGuard: initialProductSpecData?.sideGuard ?? '',
    footandheadPanel: initialProductSpecData?.footandheadPanel ?? '',
    temperatureControl: initialProductSpecData?.temperatureControl ?? '',
    top: initialProductSpecData?.top ?? '',
    foodTray: initialProductSpecData?.foodTray ?? '',
    traycorpse: initialProductSpecData?.traycorpse ?? '',
    pillowthecorpse: initialProductSpecData?.pillowthecorpse ?? '',
    lightPole: initialProductSpecData?.lightPole ?? '',
    sterilizing: initialProductSpecData?.sterilizing ?? '',
    filter: initialProductSpecData?.filter ?? '',
    underPressure: initialProductSpecData?.underPressure ?? '',
    foundationTray: initialProductSpecData?.foundationTray ?? '',
    door: initialProductSpecData?.door ?? '',
    handle: initialProductSpecData?.handle ?? '',
    medicineBox: initialProductSpecData?.medicineBox ?? '',
    handleTrolley: initialProductSpecData?.handleTrolley ?? '',
    drawer: initialProductSpecData?.drawer ?? '',
    specremarks: initialProductSpecData.specremarks ?? '',
  };
}
